Config = {}

Config = {
    --- APPARENCE BANNIERE
    ColorMenuR = 245, 
    ColorMenuG = 82, 
    ColorMenuB = 255,
    ColorMenuA = 180,
    Bannierperso = false,      
    BannerPerso = "commonmenu",   
    BannerPerso2 = "interaction_bgd",    
    --- LICENSES           
    CodeDeLaRoute = "dmv",          
    PPA = "ppa",                    
    Drive = "drive",                
    Truck = "truck",                
    Moto = "moto",                  
    Boat = "boat",                  
    Plane = "plane",   
    --- ACTIONS DISPONIBLES / true pour oui / false pour non
    SystemeReport = true,                    
    GestionJoueur = true,         
    GestionPersonnel = true,       
    GestionVeh = true,   
    GestionAdministration = true,  
    GestionDev = true,
    GestionGrade = true,            
    GestionStaff = true,           
    Invisible = true,     
    SystemeWarn = true,           
    SystemeKick = true,           
    SystemeBan = true,             
    SystemeWype = true,  
    MenuPed = true,  
    Armas = true,  
    Viosionas = true,                          
    GPB = true,                     
    Vision = true,
    Raccourcis = true,                  
    Drift = true,                   
    Super = true,               
    Heal = true, 
    GodMod = true,            
    GivePermis = true,              
    GiveArgent = true,              
    GiveItem = true,                
    Teleportation = true,    
    SpawnCar = true,       
    DelGun = true,                  
    AfficherBlips = true,           
    AfficherNom = true,             
    NoClip = true,                  
    RageUIInfo = true,            
    Spectate = true,                
    TPJoueur = true,                
    Freeze = true,               
    SendMessage = true,            
    OpenInventaire = true,        
    Revive = true,                      
    GPBJoueur = true,               
    PositionGPS = true,             
    License = true,                
    GiveItemJoueur = true,         
    GivePermisJoueur = true,       
    GiveArgentJoueur = true,      
    Sanctions = true,
    SetJob = true,             
    VoirItem = true,               
    VoirArme = true,               
    ViderInventaire = true,    
    ViderArme = true,       
    Annonce = true,              
    KickAll = true,      
    ReviveAll = true,          
    ClearChat = true,     
    Meteo = true,           
    Coords = true,                
    CreerMarker = true,           
    CreerBlips = true,            
    CreerItem = true,              
    NameStreet = true,              
    GestionRessource = true,        
    SpawnVeh = true,                
    VehEnFace = true,              
    DeleteVeh = true,             
    Repair = true,              
    ModifSale = true,            
    PleinVeh = true,               
    VehInvisible = true,          
    Plaque = true,                
    Livery = true,  
    --- COMMANDES A MODIFIER SELON VOTRE SERVEUR
    CommandClearInventory = "clearinventory",  
    CommandRevive = "revive", 
    CommandClearLoadout = "clearloadout",  
    ClearAllCommand = "clearall",    
    --- AUTRES               
    KeyMenu = 'F10',  
    NotifConnectionJoueur = true,   
    NotifPriseService = true,       
    ESextendedLegacy = true,                  
    --- LOCALISATION DE TELEPORTATION    
    Police = {position = {408.6676, -995.697, 29.266}},     
    Strip = {position = {129.7895, -1300.30, 29.232}},
    --- PERMISSIONS
    PermGestionJoueur = "0",             
    PermGestionPersonnel = "0",     
    PermGestionVeh = "0",     
    PermGestionAdministration = "0",       
    PermGestionReport = "0",               
    PermGestionDev = "0",                  
    PermGestionGrade = "0",              
    PermGestionStaff = "0",              
    PermInvisible = "0",
    PermNoClip = "0",
    PermAfficherNom = "0",
    PermAfficherBlips = "0",
    PermDelGun = "0",
    PermTeleportation = "0",
    PermSpawnCar = "0",
    PermHeal = "0",
    PermGodMod = "0",
    PermSuper = "0",
    PermDrift = "0",
    PermVision = "0",
    PermRaccourcis = "0",
    PermGPB = "0",
    PermGive = "0",
    PermMenuPed = "0",
    PermArmas = "0",
    PermViosionas = "0",
    PermSpectate = "0",
    PermTPJoueur = "0",
    PermFreeze = "0",
    PermSendMessage = "0",
    PermOpenInventaire = "0",
    PermRevive = "0",
    PermGPBJoueur = "0",
    PermLicense = "0",
    PermGPS = "0",
    PermGiveJoueur = "0",
    PermSanctions = "0",
    PermSetJob = "0",
    PermAddStaff = "0",
    PermWype = "0",
    PermWarn = "0",
    PermKick = "0",
    PermBan = "0",
    PermClearInventaire = "0",
    PermDeleteWarn = "0",
    PermDeleteKick = "0",
    PermDeleteBan = "0",
    PermAnnonce = "0",
    PermKickAll = "0",
    PermReviveAll = "0",
    PermBanActif = "0",
    PermClearChat = "0",
    PermMeteo = "0",
    PermPrendreEnCharge = "0",
    PermTraiterReport = "0",
    PermDeleteReport = "0",
    PermReouvrirReport = "0",
    PermCreerMarker = "0",
    PermCreerBlips = "0",
    PermCreerItem = "0",
    PermNameStreet = "0",
    PermGestionRessource = "0",
    PermSpawnVeh = "0",
    PermVehEnFace = "0",
    PermDeleteVeh = "0",
    PermRepair = "0",
    PermModifSale = "0",
    PermPleinVeh = "0",
    PermVehInvisible = "0",
    PermPlaque = "0",
    PermLivery = "0",
    PermOpenMenu = "0",
    PermDeleteBanActif = "0",
    --- LOGS DISCORD
    Logs = {
        PriseFinService = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        ActionPersonnel = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        GestionTime = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        GestionJoueur = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        Administration = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        Divers = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        GestionDev = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
        GestionVeh = "https://discord.com/api/webhooks/1318636426904211547/MPPwF7McGJJEZUuShEiwDDpOpFLgAoWNvk0zY4FFbl4j6gSs2kNn_PjXd-d5olWEbr-V",
    },
}
menu = {                                                               
	menuped = {                                                         
        menuped = {   
            --- A VOUS D'AJOUTER LES PEDS DE VOTRE CHOIX                                                  
			{minidesc = "A CONFIG", ped = "a_m_o_soucent_02"}, 
        }
    }
}
armes = {
    arme = {
        arme = {
            {nom = "Fusil Avancé (weapon_advancedrifle)", arme = "weapon_advancedrifle"},
            {nom = "Pistolet Automatique (weapon_appistol)", arme = "weapon_appistol"},
            {nom = "Fusil d'Assaut (weapon_assaultrifle)", arme = "weapon_assaultrifle"},
            {nom = "Fusil d'Assaut [MKII] (weapon_assaultrifle_mk2)", arme = "weapon_assaultrifle_mk2"},
            {nom = "Fusil à Pompe d'Assaut (weapon_assaultshotgun)", arme = "weapon_assaultshotgun"},
            {nom = "Mitraillette d'Assaut (weapon_assaultsmg)", arme = "weapon_assaultsmg"},
            {nom = "Fusil à Pompe Automatique (weapon_autoshotgun)", arme = "weapon_autoshotgun"},
            {nom = "Balle de BaseBall (weapon_ball)", arme = "weapon_ball"},
            {nom = "Batte (weapon_bat)", arme = "weapon_bat"},
            {nom = "Hâche de Combat (weapon_battleaxe)", arme = "weapon_battleaxe"},
            {nom = "Bouteille (weapon_bottle)", arme = "weapon_bottle"},
            {nom = "Fusil Bullpup (weapon_bullpuprifle)", arme = "weapon_bullpuprifle"},
            {nom = "Fusil Bullpup [MKII] (weapon_bullpuprifle_mk2)", arme = "weapon_bullpuprifle_mk2"},
            {nom = "Fusil à Pompe Bullpup (weapon_bullpupshotgun)", arme = "weapon_bullpupshotgun"},
            {nom = "Fusil Carabine (weapon_carbinerifle)", arme = "weapon_carbinerifle"},
            {nom = "Fusil Carabine [MKII] (weapon_carbinerifle_mk2)", arme = "weapon_carbinerifle_mk2"},
            {nom = "Mitrailleuse de Combat (weapon_combatmg)", arme = "weapon_combatmg"},
            {nom = "Mitrailleuse de Combat [MKII] (weapon_combatmg_mk2)", arme = "weapon_combatmg_mk2"},
            {nom = "ADP de Combat (weapon_combatpdw)", arme = "weapon_combatpdw"},
            {nom = "Pistolet de Combat (weapon_combatpistol)", arme = "weapon_combatpistol"},
            {nom = "Lande Grenades Compact (weapon_compactlauncher)", arme = "weapon_compactlauncher"},
            {nom = "Fusil Compact (weapon_compactrifle)", arme = "weapon_compactrifle"},
            {nom = "Pied de Biche (weapon_crowbar)", arme = "weapon_crowbar"},
            {nom = "Dague Antique (weapon_dagger)", arme = "weapon_dagger"},
            {nom = "Fusil à Double Canon (weapon_dbshotgun)", arme = "weapon_dbshotgun"},
            {nom = "Revolver Double Action(weapon_doubleaction)", arme = "weapon_doubleaction"},
            {nom = "Extincteur (weapon_fireextinguisher)", arme = "weapon_fireextinguisher"},
            {nom = "Lanceur Pyrotechnique (weapon_firework)", arme = "weapon_firework"},
            {nom = "Fusée éclairante (weapon_flare)", arme = "weapon_flare"},
            {nom = "Pistolet de Détresse (weapon_flaregun)", arme = "weapon_flaregun"},
            {nom = "Lampe de Poche(weapon_flashlight)", arme = "weapon_flashlight"},
            {nom = "Pistolet Perico (weapon_gadgetpistol)", arme = "weapon_gadgetpistol"},
            {nom = "Club de Golf (weapon_golfclub)", arme = "weapon_golfclub"},
            {nom = "Grenades (weapon_grenade)", arme = "weapon_grenade"},
            {nom = "Lance Grenades (weapon_grenadelauncher)", arme = "weapon_grenadelauncher"},
            {nom = "Sulfateuse Gusenberg (weapon_gusenberg)", arme = "weapon_gusenberg"},
            {nom = "Marteau (weapon_hammer)", arme = "weapon_hammer"},
            {nom = "Hachette (weapon_hatchet)", arme = "weapon_hatchet"},
            {nom = "Pistolet Lourd (weapon_heavypistol)", arme = "weapon_heavypistol"},
            {nom = "Fusil à Pompe Lourd (weapon_heavyshotgun)", arme = "weapon_heavyshotgun"},
            {nom = "Fusil de Précision Lourd (weapon_heavysniper)", arme = "weapon_heavysniper"},
            {nom = "Fusil de Précision Lourd [MKII] (weapon_heavysniper_mk2)", arme = "weapon_heavysniper_mk2"},
            {nom = "Lance Missiles (weapon_hominglauncher)", arme = "weapon_hominglauncher"},
            {nom = "Couteau (weapon_knife)", arme = "weapon_knife"},
            {nom = "Poing Américain (weapon_knuckle)", arme = "weapon_knuckle"},
            {nom = "Machette (weapon_machete)", arme = "weapon_machete"},
            {nom = "Pistolet Mitrailleur (weapon_machinepistol)", arme = "weapon_machinepistol"},
            {nom = "Pistolet de Précision (weapon_marksmanpistol)", arme = "weapon_marksmanpistol"},
            {nom = "Fusil à Lunette (weapon_marksmanrifle)", arme = "weapon_marksmanrifle"},
            {nom = "Fusil à Lunette [MKII] (weapon_marksmanrifle_mk2)", arme = "weapon_marksmanrifle_mk2"},
            {nom = "Mitrailleuse (weapon_mg)", arme = "weapon_mg"},
            {nom = "Pistolet Mitrailleur (weapon_microsmg)", arme = "weapon_microsmg"},
            {nom = "Minigun (weapon_minigun)", arme = "weapon_minigun"},
            {nom = "Mitrailleuse Légère (weapon_minismg)", arme = "weapon_minismg"},
            {nom = "Molotov (weapon_molotov)", arme = "weapon_molotov"},
            {nom = "Mousquet (weapon_musket)", arme = "weapon_musket"},
            {nom = "Matraque (weapon_nightstick)", arme = "weapon_nightstick"},
            {nom = "Bidon d'Essence (weapon_petrolcan)", arme = "weapon_petrolcan"},
            {nom = "Bombe Artisanale (weapon_pipebomb)", arme = "weapon_pipebomb"},
            {nom = "Pistolet (weapon_pistol)", arme = "weapon_pistol"},
            {nom = "Pistolet [MKII] (weapon_pistol_mk2)", arme = "weapon_pistol_mk2"},
            {nom = "Pistolet Calibre 50 (weapon_pistol50)", arme = "weapon_pistol50"},
            {nom = "Queue de Billard (weapon_poolcue)", arme = "weapon_poolcue"},
            {nom = "Mine de Proximité (weapon_proxmine)", arme = "weapon_proxmine"},
            {nom = "Fusil à Pompe (weapon_pumpshotgun)", arme = "weapon_pumpshotgun"},
            {nom = "Fusil à Pompe [MKII] (weapon_pumpshotgun_mk2)", arme = "weapon_pumpshotgun_mk2"},
            {nom = "Fusil à Impulsion (weapon_railgun)", arme = "weapon_railgun"},
            {nom = "Dézingator Infernal (weapon_raycarbine)", arme = "weapon_raycarbine"},
            {nom = "Destructeur de l'Infini (weapon_rayminigun)", arme = "weapon_rayminigun"},
            {nom = "Up-n-Atomisateur (weapon_raypistol)", arme = "weapon_raypistol"},
            {nom = "Revolver Lourd (weapon_revolver)", arme = "weapon_revolver"},
            {nom = "Revolver Lourd [MKII] (weapon_revolver_mk2)", arme = "weapon_revolver_mk2"},
            {nom = "Lance Roquettes (weapon_rpg)", arme = "weapon_rpg"},
            {nom = "Fusil à Canon Scié (weapon_sawnoffshotgun)", arme = "weapon_sawnoffshotgun"},
            {nom = "Mitraillette (weapon_smg)", arme = "weapon_smg"},
            {nom = "Mitraillette [MKII] (weapon_smg_mk2)", arme = "weapon_smg_mk2"},
            {nom = "Fusil de Précision (weapon_sniperrifle)", arme = "weapon_sniperrifle"},
            {nom = "Boule de Neige (weapon_snowball)", arme = "weapon_snowball"},
            {nom = "Pétoire (weapon_snspistol)", arme = "weapon_snspistol"},
            {nom = "Pétoire [MKII] (weapon_snspistol_mk2)", arme = "weapon_snspistol_mk2"},
            {nom = "Carabine Spéciale (weapon_specialcarbine)", arme = "weapon_specialcarbine"},
            {nom = "Carabien Spéciale [MKII] (weapon_specialcarbine_mk2)", arme = "weapon_specialcarbine_mk2"},
            {nom = "Bombe Collante (weapon_stickybomb)", arme = "weapon_stickybomb"},
            {nom = "Hachette en Pierre (weapon_stone_hatchet)", arme = "weapon_stone_hatchet"},
            {nom = "Pistolet Paralysant (weapon_stungun)", arme = "weapon_stungun"},
            {nom = "Cran d'Ârret (weapon_switchblade)", arme = "weapon_switchblade"},
            {nom = "Pistolet Vintage (weapon_vintagepistol)", arme = "weapon_vintagepistol"},
            {nom = "Clé Anglaise (weapon_wrench)", arme = "weapon_wrench"},
            
        }
    }
}

function CSWipeTable(srcid)
    MySQL.Sync.execute("DELETE FROM user_inventory WHERE identifier='" ..srcid.. "'")
    MySQL.Sync.execute("DELETE FROM owned_vehicles WHERE owner='" ..srcid.. "'")
end

function ShowNotification(texte)
    ESX.ShowNotification(texte)
end

function ShowNotificationServer(source, texte)
    TriggerClientEvent('esx:showNotification', source, texte)
end

function ShowAdvencedNotificationServer(source, titre, soustitre, description)
    TriggerClientEvent('esx:showAdvancedColoredNotification', source, titre, soustitre, description, "CHAR_GANGAPP", 1, 27)
end

Config.ForceSteam        = true    
Config.MultiServerSync   = false  
